import { useState, useEffect } from 'react'
import { X, Save, RotateCcw, Clock, Trash2, Download, Upload, Check, AlertCircle, Shield, Settings, Zap } from 'lucide-react'
import { useAppStore } from '../store/useAppStore'
import { cn } from '../lib/utils'

export default function BackupRestore() {
  const { showBackupModal, setShowBackupModal, chapters, outline, characters, worldSettings, novelInfo, setShowToast } = useAppStore()
  const [backups, setBackups] = useState([])
  const [isLoading, setIsLoading] = useState(false)
  const [autoBackup, setAutoBackup] = useState(false)
  const [lastAutoBackup, setLastAutoBackup] = useState(null)

  useEffect(() => {
    if (showBackupModal) {
      loadBackups()
    }
  }, [showBackupModal])

  const loadBackups = () => {
    const savedBackups = JSON.parse(localStorage.getItem('integrated-author-backups') || '[]')
    setBackups(savedBackups)
    
    const settings = JSON.parse(localStorage.getItem('integrated-author-settings') || '{}')
    setAutoBackup(settings.autoBackup || false)
    setLastAutoBackup(settings.lastAutoBackup || null)
  }

  const createBackup = () => {
    setIsLoading(true)
    
    try {
      const backup = {
        id: Date.now().toString(),
        name: `备份 ${new Date().toLocaleString()}`,
        createdAt: new Date().toISOString(),
        data: {
          chapters,
          outline,
          characters,
          worldSettings,
          novelInfo
        },
        size: JSON.stringify({ chapters, outline, characters, worldSettings, novelInfo }).length,
        version: 2,
        autoGenerated: false
      }
      
      const savedBackups = JSON.parse(localStorage.getItem('integrated-author-backups') || '[]')
      savedBackups.unshift(backup)
      
      if (savedBackups.length > 10) {
        savedBackups.pop()
      }
      
      localStorage.setItem('integrated-author-backups', JSON.stringify(savedBackups))
      setBackups(savedBackups)
      setShowToast('备份创建成功！', 'success')
    } catch (error) {
      console.error('备份失败:', error)
      setShowToast('备份失败：' + error.message, 'error')
    } finally {
      setIsLoading(false)
    }
  }

  const restoreBackup = (backupId) => {
    const savedBackups = JSON.parse(localStorage.getItem('integrated-author-backups') || '[]')
    const backup = savedBackups.find(b => b.id === backupId)
    
    if (!backup) {
      setShowToast('未找到备份', 'error')
      return
    }
    
    if (!confirm('确定要恢复此备份吗？当前未保存的内容将会丢失。')) {
      return
    }
    
    try {
      const { setChapters, setOutline, setCharacters, setWorldSettings, setNovelInfo } = useAppStore.getState()
      
      setChapters(backup.data.chapters || [])
      setOutline(backup.data.outline || '')
      setCharacters(backup.data.characters || [])
      setWorldSettings(backup.data.worldSettings || [])
      setNovelInfo(backup.data.novelInfo || {})
      
      setShowToast('恢复成功！', 'success')
      setShowBackupModal(false)
    } catch (error) {
      console.error('恢复失败:', error)
      setShowToast('恢复失败：' + error.message, 'error')
    }
  }

  const deleteBackup = (backupId) => {
    if (!confirm('确定要删除此备份吗？此操作不可恢复。')) {
      return
    }
    
    const savedBackups = JSON.parse(localStorage.getItem('integrated-author-backups') || '[]')
    const filtered = savedBackups.filter(b => b.id !== backupId)
    localStorage.setItem('integrated-author-backups', JSON.stringify(filtered))
    setBackups(filtered)
    setShowToast('备份已删除', 'info')
  }

  const exportBackup = (backup) => {
    const blob = new Blob([JSON.stringify(backup, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `backup-${backup.name.replace(/[<>:"/\\|?*]/g, '-')}.json`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    setShowToast('备份已导出', 'success')
  }

  const exportAllData = () => {
    const allData = {
      version: 2,
      exportTime: new Date().toISOString(),
      settings: JSON.parse(localStorage.getItem('integrated-author-settings') || '{}'),
      backups: JSON.parse(localStorage.getItem('integrated-author-backups') || '[]'),
      state: useAppStore.getState()
    }
    
    const blob = new Blob([JSON.stringify(allData, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `full-backup-${new Date().toISOString().split('T')[0]}.json`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    setShowToast('完整数据已导出', 'success')
  }

  const importBackup = (event) => {
    const file = event.target.files?.[0]
    if (!file) return
    
    const reader = new FileReader()
    reader.onload = (e) => {
      try {
        const backup = JSON.parse(e.target.result)
        
        if (!backup.data || !backup.data.chapters) {
          throw new Error('无效的备份文件')
        }
        
        const savedBackups = JSON.parse(localStorage.getItem('integrated-author-backups') || '[]')
        
        backup.id = Date.now().toString()
        backup.name = `导入: ${backup.name || file.name}`
        
        savedBackups.unshift(backup)
        
        if (savedBackups.length > 10) {
          savedBackups.pop()
        }
        
        localStorage.setItem('integrated-author-backups', JSON.stringify(savedBackups))
        setBackups(savedBackups)
        setShowToast('备份导入成功！', 'success')
      } catch (error) {
        console.error('导入失败:', error)
        setShowToast('导入失败：' + error.message, 'error')
      }
    }
    reader.readAsText(file)
  }

  const toggleAutoBackup = () => {
    const newValue = !autoBackup
    setAutoBackup(newValue)
    
    const settings = JSON.parse(localStorage.getItem('integrated-author-settings') || '{}')
    settings.autoBackup = newValue
    localStorage.setItem('integrated-author-settings', JSON.stringify(settings))
    
    setShowToast(newValue ? '已开启自动备份' : '已关闭自动备份', 'success')
  }

  const clearAllBackups = () => {
    if (confirm('确定要删除所有备份吗？此操作不可恢复。')) {
      localStorage.removeItem('integrated-author-backups')
      setBackups([])
      setShowToast('所有备份已清除', 'info')
    }
  }

  const getBackupStats = () => {
    const totalSize = backups.reduce((sum, b) => sum + (b.size || 0), 0)
    return {
      count: backups.length,
      totalSize: (totalSize / 1024).toFixed(1)
    }
  }

  if (!showBackupModal) return null

  const stats = getBackupStats()

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/50" onClick={() => setShowBackupModal(false)} />
      
      <div className="relative bg-bg-primary rounded-xl shadow-lg w-full max-w-4xl max-h-[90vh] overflow-hidden">
        <div className="flex items-center justify-between p-4 border-b border-border">
          <div className="flex items-center gap-3">
            <Shield className="w-6 h-6 text-primary" />
            <h2 className="text-lg font-semibold">备份与恢复</h2>
            <span className="text-sm text-text-muted">({stats.count} 个备份)</span>
          </div>
          <button 
            onClick={() => setShowBackupModal(false)}
            className="p-2 hover:bg-bg-tertiary rounded-lg"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 overflow-y-auto max-h-[calc(90vh-180px)]">
          <div className="space-y-6">
            {/* 快速操作 */}
            <div className="grid grid-cols-3 gap-4">
              <button
                onClick={createBackup}
                disabled={isLoading}
                className={cn(
                  "flex flex-col items-center gap-2 p-4 bg-primary text-white rounded-lg hover:bg-primary-hover transition-all",
                  isLoading && "opacity-70"
                )}
              >
                <Save className="w-6 h-6" />
                <span className="text-sm font-medium">创建备份</span>
              </button>
              
              <label className="flex flex-col items-center gap-2 p-4 bg-secondary text-white rounded-lg hover:opacity-90 transition-all cursor-pointer">
                <Upload className="w-6 h-6" />
                <span className="text-sm font-medium">导入备份</span>
                <input
                  type="file"
                  accept=".json"
                  onChange={importBackup}
                  className="hidden"
                />
              </label>
              
              <button
                onClick={exportAllData}
                className="flex flex-col items-center gap-2 p-4 bg-info text-white rounded-lg hover:opacity-90 transition-all"
              >
                <Download className="w-6 h-6" />
                <span className="text-sm font-medium">导出全部数据</span>
              </button>
            </div>

            {/* 自动备份设置 */}
            <div className="flex items-center justify-between p-4 bg-bg-secondary rounded-lg border border-border">
              <div className="flex items-center gap-3">
                <Zap className="w-5 h-5 text-primary" />
                <div>
                  <h3 className="font-medium">自动备份</h3>
                  <p className="text-sm text-text-muted">
                    每30分钟自动备份一次
                    {lastAutoBackup && ` · 上次: ${new Date(lastAutoBackup).toLocaleString()}`}
                  </p>
                </div>
              </div>
              <button
                onClick={toggleAutoBackup}
                className={cn(
                  "relative w-12 h-6 rounded-full transition-colors",
                  autoBackup ? "bg-primary" : "bg-gray-300"
                )}
              >
                <span 
                  className={cn(
                    "absolute top-1 w-4 h-4 bg-white rounded-full transition-transform",
                    autoBackup ? "left-7" : "left-1"
                  )}
                />
              </button>
            </div>

            {/* 备份统计 */}
            <div className="grid grid-cols-2 gap-4 p-4 bg-bg-secondary rounded-lg">
              <div className="text-center">
                <div className="text-2xl font-bold text-primary">{stats.count}</div>
                <div className="text-sm text-text-muted">备份数量</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-secondary">{stats.totalSize} KB</div>
                <div className="text-sm text-text-muted">占用空间</div>
              </div>
            </div>

            {/* 备份列表 */}
            <div>
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-medium">备份历史</h3>
                {backups.length > 0 && (
                  <button
                    onClick={clearAllBackups}
                    className="text-sm text-danger hover:underline flex items-center gap-1"
                  >
                    <Trash2 className="w-3 h-3" />
                    清空全部
                  </button>
                )}
              </div>

              {backups.length === 0 ? (
                <div className="text-center py-16 text-text-muted border-2 border-dashed border-border rounded-lg">
                  <Clock className="w-12 h-12 mx-auto mb-3 opacity-50" />
                  <p className="text-lg font-medium mb-2">暂无备份记录</p>
                  <p className="text-sm">点击上方按钮创建第一个备份</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {backups.map((backup) => (
                    <div
                      key={backup.id}
                      className="flex items-center justify-between p-4 border border-border rounded-lg hover:bg-bg-secondary transition-colors"
                    >
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-1">
                          <h4 className="font-medium">{backup.name}</h4>
                          {backup.autoGenerated && (
                            <span className="text-xs px-2 py-0.5 bg-primary/10 text-primary rounded">
                              自动
                            </span>
                          )}
                        </div>
                        <div className="flex items-center gap-4 text-sm text-text-muted">
                          <span className="flex items-center gap-1">
                            <Clock className="w-3 h-3" />
                            {new Date(backup.createdAt).toLocaleString()}
                          </span>
                          <span>{((backup.size || 0) / 1024).toFixed(1)} KB</span>
                          <span>{backup.data.chapters?.length || 0} 章节</span>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <button
                          onClick={() => restoreBackup(backup.id)}
                          className="p-2 hover:bg-primary/10 rounded-lg text-primary transition-colors"
                          title="恢复此备份"
                        >
                          <RotateCcw className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => exportBackup(backup)}
                          className="p-2 hover:bg-bg-tertiary rounded-lg"
                          title="导出备份"
                        >
                          <Download className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => deleteBackup(backup.id)}
                          className="p-2 hover:bg-danger/10 rounded-lg text-danger transition-colors"
                          title="删除备份"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* 提示信息 */}
            <div className="p-4 bg-info/10 border border-info/30 rounded-lg">
              <div className="flex items-start gap-3">
                <AlertCircle className="w-5 h-5 text-info flex-shrink-0 mt-0.5" />
                <div className="text-sm text-info space-y-1">
                  <p className="font-medium">💡 使用提示</p>
                  <ul className="list-disc list-inside space-y-1 ml-2">
                    <li>建议定期手动备份重要数据</li>
                    <li>系统最多保留10个本地备份</li>
                    <li>可导出备份文件进行云存储或迁移</li>
                    <li>登录后可使用云同步功能实现自动备份</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="flex justify-end gap-3 p-4 border-t border-border bg-bg-secondary">
          <button 
            onClick={() => setShowBackupModal(false)}
            className="px-6 py-2 text-sm text-text-secondary hover:text-text-primary transition-colors"
          >
            关闭
          </button>
        </div>
      </div>
    </div>
  )
}